Use true.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,7 +33,6 @@ jobs:
 
       - name: Check output for error
         run: |
-          echo "${{ fromJSON(steps.build.outputs.OUTPUT) }}" | grep -c -i error
-          #count=$(echo "${{ fromJSON(steps.build.outputs.OUTPUT) }}" | grep -c -i error)
-          #echo "$count"
+          count=$(echo "${{ fromJSON(steps.build.outputs.OUTPUT) }}" | grep -c -i error) || true
+          echo "$count"
           #if [ "$count" -gt 0 ]; then exit 1; fi
